### ISSUE TITLE
Problems executing m2tex 

### ISSUE THREAD

**Issue by kris9013** [Joao-Peterson/Math2Tex#2]
Windows 10 pro-1909
Mathcad prime 5.0

I am unable to execute the m2tex.exe from cmd, Git Bash and getting the following error cmd:  

Directory of C:\Users\krist\OneDrive\Skrivebord\Math2Tex-master
C:\Users\krist\OneDrive\Skrivebord\Math2Tex-master> m2tex.exe -h
Access is denied.

And using Git Bash I got no output or error

**Comment by Joao-Peterson** [comment]
It's probably because my binary has ownership by default. Have you tried executing as administrator? In any case ff it doesn't work i will update the release tar.gz, so try downloading again. If you have any more problems please feel free to open another issue, and if is relevant, don't forget to use the -d option and send the log file.

**Comment by kris9013** [comment]
It works now. Thanks

**Comment by Joao-Peterson** [comment]
Nice. ^_^

**Comment by kris9013** [comment]
Hi again

I have a new problem. I have generated some latexfiles using your program. The output file is not completely the same as the mathcad file. How can that be ? 

![1](https://user-images.githubusercontent.com/40248669/89885497-72421980-dbcb-11ea-9926-73bc10166f89.PNG)


![image](https://user-images.githubusercontent.com/40248669/89885736-cd740c00-dbcb-11ea-8a84-6b91a4dbf71b.png)
