### ISSUE TITLE
generated math

### ISSUE THREAD

**Issue by kris9013** [Joao-Peterson/Math2Tex#3]
Hi again

I have a new problem. I have generated some latexfiles using your program. The output file is not completely the same as the mathcad file. How can that be ?

![image](https://user-images.githubusercontent.com/40248669/90001692-0a0a3b00-dc92-11ea-92ce-05395702511e.png)

![image](https://user-images.githubusercontent.com/40248669/90001715-12627600-dc92-11ea-8545-9c785f3cab69.png)

**Comment by Joao-Peterson** [comment]
Yes, glad you asked. It might be strange but i did code it this way, the latex output doesn't sees the position of the original mathcad regions, every region is going to be a new line in the output. I did it like this because i focused my output latex to be more towards mathematical formulation and proofs, and that means for me that every equation must be in a new line. At the moment i'm refactoring the code and i want to add this mirror like positioning from the original file to the latex output.
